config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    # validates_presence_of :author, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            redirect_to root_path, notice: 'Book created successfully!'
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @book.update(book_params)
            redirect_to root_path, notice: 'Book updated successfully!'
        else
            render :edit
        end
    end

    def destroy
        @book.destroy
        redirect_to root_path, notice: 'Book deleted successfully!'
    end

    private

    def book_params
        params.require(:book).permit(:author, :title)
    end

    def set_book
        @book = Book.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, id: "book-form") do |f| %>
    <div>
        <%= f.label :author %>
        <%= f.text_field :author %>
    </div>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.submit 'Submit' %>
    </div>
<%end%>

app/views/books/edit.html.erb
<h1> Edit book </h1>
<%= render 'form' %>
<br>
<% link_to 'Back', root_path %>

app/views/books/index.html.erb
<h1> List of Books! </h1>

<% if @books.any? %>
    <table>
        <tr>
            <th>Author</th>
            <th>Title</th>
            <th>Action</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
            <td><%= book.author %></td>
            <td><%= book.title %></td>
            <td>
                <%= link_to 'Show', book_path(book) %>
                <%= link_to 'Edit', edit_book_path(book) %>
                <%= link_to 'Delete', book_path(book), data: { "turbo-method": :delete } %>
            </td>
        </tr>
        <%end%>
    </table>
<% else %>
<p>No books found in here!</p>
<%end%>
<br>
<%= link_to 'New', new_book_path %>


<p>lorem ipsum bla bla lorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla
lorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla
lorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla</p>

app/views/books/new.html.erb
<h1> New book </h1>
<%= render 'form' %>
<br>
<% link_to 'Back', root_path %>

<p>lorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla
lorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla
lorem ipsum bla blalorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla
lorem ipsum bla blalorem ipsum bla blalorem ipsum bla bla</p>

app/views/books/show.html.erb
<h1>Author: <%= @book.author%></h1>
<h1>Title: <%= @book.title%></h1>
<br>
<%= link_to 'Edit', edit_book_path %>
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MysqlPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>